[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Branch staging — pakai environment variables berbeda
[context.staging]
  command = "npm run build"

[context.production]
  command = "npm run build"

# Redirect semua ke Next.js handler
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
